# Generated by Django 3.2.3 on 2021-05-23 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='votes',
            field=models.ManyToManyField(related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petition',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petition',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datetime created'),
        ),
        migrations.DeleteModel(
            name='PetitionUser',
        ),
    ]
