# Generated by Django 3.2.3 on 2021-05-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_votes_petition_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='image',
        ),
        migrations.AddField(
            model_name='petition',
            name='description',
            field=models.CharField(default='temp', max_length=200, verbose_name='Petition'),
            preserve_default=False,
        ),
    ]
